Moved check on code style in pre-commit hook
Before, the check on code style was done after adjusting trailing
spaces or newlines and this could lead to false violation of code style
rules.

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -150,6 +150,40 @@ if [ $(git diff --cached --name-only --diff-filter=A -z $againstSHAToCompareWidt
 fi
 
 #-----------------------------------------------------------------------------
+# Get list of staged files which have to be checked with respect to CODE STYLE
+readonly listOfFilesToBeChecked=( $(git diff-index --cached --name-only HEAD --diff-filter=ACMR | grep -e "\.c$" -e "\.cpp$" -e "\.h$" -e "\.hpp$" -e "\.cl$") )
+if [ ${#listOfFilesToBeChecked[@]} -ne 0 ]; then
+    # Check for existence of clang-format, and error out if not present
+    if ! builtin type -P clang-format >>/dev/null; then
+        AbortCommit "The program \"clang-format\" was not found!" GiveAdviceAboutClangFormat
+    else
+        errecho "\n"
+        errecho "Checking style of code... " 39
+        readonly clangFormatParameters="-style=file"
+        filesWithCodeStyleErrors=()
+        for file in "${listOfFilesToBeChecked[@]}"; do
+            # nf is the temporary checkout. This makes sure we check against the
+            # revision in the index (and not the checked out version)
+            nf=$(git checkout-index --temp ${file} | cut -f 1)
+            newfile=$(mktemp /tmp/${nf}.XXXXXX) || exit ${CL2QCD_failureExitCode}
+            clang-format ${clangFormatParameters} ${nf} > ${newfile} 2>> /dev/null
+            diff  "${nf}" "${newfile}" >>/dev/null
+            exitCode=$?
+            rm "${newfile}"
+            rm "${nf}"
+            if [ ${exitCode} != 0 ] ; then
+                filesWithCodeStyleErrors+=( "${file}" )
+            fi
+        done
+        if [ ${#filesWithCodeStyleErrors[@]} -ne 0 ]; then
+            echo; AbortCommit "Code style error found!" PrintReportOnFilesWithStyleErrors "${filesWithCodeStyleErrors[@]}"
+        else
+            errecho " done!\n" 39
+        fi
+    fi
+fi
+
+#-----------------------------------------------------------------------------
 # Work on tab/spaces in files (only those fully stages, since after
 # modification we have to add them and if done on partially staged
 # they would be then fully staged against user willing!
@@ -190,6 +224,7 @@ if [ ${#fullyStagedFiles[@]} -ne 0 ]; then
         git add "$file"
     done
 fi
+
 #-----------------------------------------------------------------------------
 # Check CL2QCD header in staged files
 if [ ${#stagedFiles[@]} -ne 0 ]; then
@@ -234,38 +269,4 @@ fi
 #If there are still whitespace errors, print the offending file names and fail.
 if ! git diff-index --check --cached $againstSHAToCompareWidth >/dev/null 2>&1; then
     AbortCommit "Whitespace errors present in staged files!" GiveAdviceAboutWhitespaceError
-fi
-
-#-----------------------------------------------------------------------------
-# Get list of staged files which have to be checked with respect to style
-readonly listOfFilesToBeChecked=( $(git diff-index --cached --name-only HEAD --diff-filter=ACMR | grep -e "\.c$" -e "\.cpp$" -e "\.h$" -e "\.hpp$" -e "\.cl$") )
-if [ ${#listOfFilesToBeChecked[@]} -ne 0 ]; then
-    # Check for existence of astyle, and error out if not present.
-    if ! builtin type -P clang-format >>/dev/null; then
-        AbortCommit "The program \"clang-format\" was not found!" GiveAdviceAboutClangFormat
-    else
-        errecho "\n"
-        errecho "Checking style of code... " 39
-        readonly clangFormatParameters="-style=file"
-        filesWithCodeStyleErrors=()
-        for file in "${listOfFilesToBeChecked[@]}"; do
-            # nf is the temporary checkout. This makes sure we check against the
-            # revision in the index (and not the checked out version).
-            nf=$(git checkout-index --temp ${file} | cut -f 1)
-            newfile=$(mktemp /tmp/${nf}.XXXXXX) || exit ${CL2QCD_failureExitCode}
-            clang-format ${clangFormatParameters} ${nf} > ${newfile} 2>> /dev/null
-            diff  "${nf}" "${newfile}" >>/dev/null
-            exitCode=$?
-            rm "${newfile}"
-            rm "${nf}"
-            if [ ${exitCode} != 0 ] ; then
-                filesWithCodeStyleErrors+=( "${file}" )
-            fi
-        done
-        if [ ${#filesWithCodeStyleErrors[@]} -ne 0 ]; then
-            echo; AbortCommit "Code style error found!" PrintReportOnFilesWithStyleErrors "${filesWithCodeStyleErrors[@]}"
-        else
-            errecho " done!\n" 39
-        fi
-    fi
 fi
